/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisisRouteImport } from './routes/analisis'
import { Route as MetodologiRouteImport } from './routes/metodologi'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SurveiRouteImport } from './routes/survei'
import { Route as TemudataRouteImport } from './routes/temudata'
import { Route as TimRouteImport } from './routes/tim'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiInsightRouteImport } from './routes/api/insight'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisisRoute = AnalisisRouteImport.update({
  id: '/analisis',
  path: '/analisis',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiRoute = MetodologiRouteImport.update({
  id: '/metodologi',
  path: '/metodologi',
  getParentRoute: () => rootRouteImport,
} as any)
const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveiRoute = SurveiRouteImport.update({
  id: '/survei',
  path: '/survei',
  getParentRoute: () => rootRouteImport,
} as any)
const TemudataRoute = TemudataRouteImport.update({
  id: '/temudata',
  path: '/temudata',
  getParentRoute: () => rootRouteImport,
} as any)
const TimRoute = TimRouteImport.update({
  id: '/tim',
  path: '/tim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightRoute = ApiInsightRouteImport.update({
  id: '/api/insight',
  path: '/api/insight',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/metodologi': typeof MetodologiRoute
  '/peta': typeof PetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survei': typeof SurveiRoute
  '/temudata': typeof TemudataRoute
  '/tim': typeof TimRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/metodologi': typeof MetodologiRoute
  '/peta': typeof PetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survei': typeof SurveiRoute
  '/temudata': typeof TemudataRoute
  '/tim': typeof TimRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisis': typeof AnalisisRoute
  '/metodologi': typeof MetodologiRoute
  '/peta': typeof PetaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survei': typeof SurveiRoute
  '/temudata': typeof TemudataRoute
  '/tim': typeof TimRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insight': typeof ApiInsightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisis'
    | '/metodologi'
    | '/peta'
    | '/sitemap.xml'
    | '/survei'
    | '/temudata'
    | '/tim'
    | '/api/chat'
    | '/api/insight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisis'
    | '/metodologi'
    | '/peta'
    | '/sitemap.xml'
    | '/survei'
    | '/temudata'
    | '/tim'
    | '/api/chat'
    | '/api/insight'
  id:
    | '__root__'
    | '/'
    | '/analisis'
    | '/metodologi'
    | '/peta'
    | '/sitemap.xml'
    | '/survei'
    | '/temudata'
    | '/tim'
    | '/api/chat'
    | '/api/insight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisisRoute: typeof AnalisisRoute
  MetodologiRoute: typeof MetodologiRoute
  PetaRoute: typeof PetaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurveiRoute: typeof SurveiRoute
  TemudataRoute: typeof TemudataRoute
  TimRoute: typeof TimRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInsightRoute: typeof ApiInsightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisis': {
      id: '/analisis'
      path: '/analisis'
      fullPath: '/analisis'
      preLoaderRoute: typeof AnalisisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologi': {
      id: '/metodologi'
      path: '/metodologi'
      fullPath: '/metodologi'
      preLoaderRoute: typeof MetodologiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survei': {
      id: '/survei'
      path: '/survei'
      fullPath: '/survei'
      preLoaderRoute: typeof SurveiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temudata': {
      id: '/temudata'
      path: '/temudata'
      fullPath: '/temudata'
      preLoaderRoute: typeof TemudataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tim': {
      id: '/tim'
      path: '/tim'
      fullPath: '/tim'
      preLoaderRoute: typeof TimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insight': {
      id: '/api/insight'
      path: '/api/insight'
      fullPath: '/api/insight'
      preLoaderRoute: typeof ApiInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisisRoute: AnalisisRoute,
  MetodologiRoute: MetodologiRoute,
  PetaRoute: PetaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurveiRoute: SurveiRoute,
  TemudataRoute: TemudataRoute,
  TimRoute: TimRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInsightRoute: ApiInsightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
